development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: library_system_development
  pool: 5
  username: postgres

test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: library_system_test
  pool: 5
  username: postgres

  production:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: library_system_production
  pool: 5
  username: postgres